export const getCvBuilderStyles = (t) => ({
  inputStyle: {
    width: "100%",
    padding: "9px 12px",
    fontSize: 13,
    borderRadius: 10,
    border: `1px solid ${t.border}`,
    background: t.inputBg,
    color: t.text,
    fontFamily: "'Cairo',sans-serif",
    outline: "none",
  },
  labelStyle: {
    fontSize: 11,
    fontWeight: 700,
    color: t.subText,
    fontFamily: "'Cairo',sans-serif",
    marginBottom: 4,
    display: "block",
  },
  cardStyle: {
    borderRadius: 14,
    padding: "14px",
    background: t.cardBg,
    border: `1px solid ${t.border}`,
    marginBottom: 12,
  },
  secHeadStyle: {
    fontSize: 13,
    fontWeight: 700,
    color: t.gold,
    fontFamily: "'Cairo',sans-serif",
    marginBottom: 10,
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  addBtnStyle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    width: "100%",
    padding: "9px",
    borderRadius: 10,
    border: `1px dashed ${t.gold}`,
    background: "transparent",
    color: t.gold,
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "'Cairo',sans-serif",
    marginTop: 8,
  },
  tagStyle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    background: `${t.gold}22`,
    color: t.gold,
    fontSize: 11,
    fontWeight: 700,
    padding: "3px 10px",
    borderRadius: 20,
    fontFamily: "'Cairo',sans-serif",
  },
  cvActionBtnStyle: (bg, color = "#fff") => ({
    width: "100%",
    padding: "13px",
    borderRadius: 12,
    border: "none",
    background: bg,
    color,
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "'Cairo',sans-serif",
    boxShadow: "0 4px 14px rgba(0,0,0,0.12)",
    transition: "opacity .2s",
  }),
  stepCircle: (isActive, isCompleted) => ({
    width: 28,
    height: 28,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 700,
    border: `2px solid ${isActive || isCompleted ? t.gold : t.border}`,
    background: isCompleted ? t.gold : isActive ? `${t.gold}22` : t.inputBg,
    color: isActive || isCompleted ? (isCompleted ? "#fff" : t.gold) : t.subText,
    transition: "all .2s",
    fontFamily: "'Cairo',sans-serif",
  }),
});
